### ISSUE TITLE
Modal UI: As a user I can enter my email so I can get a certificate

### ISSUE THREAD

**Issue by paigel** [rmx-party/choodle#162]
# Criteria
Given modal functionality in place via #157 , styling to the modal is applied

## Tasks
- [x] exit 'x'
- [x] h1
- [x] image block
- [x] body copy
- [x] email input
    * include standard states: default, error, success
- [x] primary button
- [x] link

## Design Reference
**Icon of `X` for Exit/close:
[in Notion](https://www.notion.so/rmxparty/App-icons-780defb253cb4ac39e4054c2c8e40e47?pvs=4#0b4f0dd93bb348d9afc51c91359e046c)

**Image of choodled certificate "icon"**
[in Notion](https://www.notion.so/rmxparty/Email-Modal-fc32be40fbd9448dbb3c6b36330f4c2b?pvs=4)

**See design**
[in Figma](https://www.figma.com/file/QigRM4CnB2EhfPWa4ZJZIZ/Choodle-Beta?type=design&node-id=83-60969&mode=design&t=njsooH0di9NMHJ7a-11)

**Comment by brandondees** [comment]
the close 'x' still needs attention
also, on ios safari the url bar overlays the bottom of the modal content so it should be given some bottom padding to compensate and enable user to scroll down to view it if it's not short enough to fit in view.
input with label may need some attention to detail still. right now there are a couple inline styles applied because there's no component library reference for inputs yet, but as we dial in that detail we may want to extract a re-usable and more flexible component.

**Comment by paigel** [comment]
this has been approved, thank you 🙏🏽
